version: '3.8'

services:
  backend:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-shash236}/streaksmanager/streakmanserver:latest
    container_name: streaksmanager-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-*}
    pull_policy: always
