version: '3.8'

services:
  backend:
    # Replace with your actual image path if different
    image: ghcr.io/shash236/streaksmanager/streakmanserver:latest
    container_name: streaksmanager-backend
    restart: always
    ports:
      - "8080:8080"
    # Load environment variables from the generated .env file
    env_file:
      - .env
    pull_policy: always
