spring.application.name=streakmanserver

# Database Configuration
# Database Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/streakman}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${jpa.ddl-auto:update}
spring.jpa.show-sql=true

# Security
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}

